services:
  Novactive\Bundle\EzStaticTemplatesBundle\Routing\Router:
    arguments:
      - "%ezpublish.siteaccess.groups%"
    calls:
      - [setSiteaccess, ["@ezpublish.siteaccess"]]
    tags:
      - {name: router, priority: 300}